EnsachageKara/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Products.urls')),
    path('', include('Users.urls')),
]

Products/urls.py
from django.urls import path
from .views import *

app_name = 'product'
urlpatterns = [
    path('', index_view, name='index'),
    path('details/', detail_view, name='details'),
    path('edite/', edite_view, name='edite'),
]

Users/urls.py
from django.urls import path
from .views import *

app_name = 'users'
urlpatterns = [
    path('login/', loginView, name='login'),
    path('logup/', logupView, name='logup'),
    path('logout/', logoutView, name='logout'),
]

templates/footer.html
<footer class="text-center text-white mt-4" style="background-color: #caced1;">
    <!-- Grid container -->
    <div class="container p-4">
        <!-- Section: Images -->
        <section class="">
            <div class="row">
                <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                    <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
                        <img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/113.webp" class="w-100" />
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                    <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
                        <img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/111.webp" class="w-100" />
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                    <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
                        <img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/112.webp" class="w-100" />
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                    <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
                        <img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/114.webp" class="w-100" />
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                    <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
                        <img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/115.webp" class="w-100" />
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
                        </a>
                    </div>
                </div>
                <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
                    <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
                        <img src="https://mdbcdn.b-cdn.net/img/new/fluid/city/116.webp" class="w-100" />
                        <a href="#!">
                            <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);"></div>
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Section: Images -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        <p>&copy; Copyright {% now 'Y' %} &middot; <a class="text-white" href="">Xavier ALPHA</a>,&middot; All rights reserved!</p>
        
    </div>
    <!-- Copyright -->
</footer>

templates/home.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <!-- Google Fonts Pre Connect -->
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <!-- Meta Tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Fonts Links (Roboto 400, 500 and 700 included) -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap">
    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.css" rel="stylesheet" />

    <!-- CSS Files Links -->
    <link rel="stylesheet" href="./styles.css">

    <!-- Title -->
    <title>Simple Page</title>
</head>

<body>
    <header>
        {% include 'navBar.html' %}
    </header>

    <main>
        {% block content %}

        {% endblock content %}
    </main>

    <footer>
        {% include 'footer.html' %}
    </footer>

    <noscript>Your browser don't support JavaScript!</noscript>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.2.0/mdb.min.js"></script>
</body>

</html>

templates/index.html
{% extends 'home.html' %}
{% block content %}
<div class="container">
    <p class="text-dark text-end mt-3 fs-4">To day is :{% now 'd-m-Y' %} </p>
    {% if etat_page == True %}
    <div class="row row-cols-2 mt-3">
        <div class="col">
            <div class="card">
                <div class="card-header text-center fs-3 bg-success text-light btn"><i
                        class="fas fa-rectangle-list"></i>
                    Formulaire
                </div>
                <div class="card-body">
                    {% if user.is_authenticated %}
                    <form action="" method="post"> {% csrf_token %}
                        {{ form.as_p }}
                        <div class="d-grid gap">
                            <button type="submit" class="btn btn-primary">SUBMIT</button>
                        </div>
                    </form>
                    {% else %}
                    <div class="text-center fs-2 text-dark">Veillez-vous connecter</div>
                    <div class="text-center fs-6 mt-3"><i class="fas fa-link"></i><a href="{% url 'users:login' %}">
                            Cliqué ici pour vous connecter</a></div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                {% if posts_date %}
                <div class="col">
                    <div class="card">
                        <div class="card-header fs-3 bg-primary text-center text-light btn"><i class="fas fa-book"></i>
                            Details
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead>
                                    <td colspan="2">
                                        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                                            <div class="container-fluid">
                                                <form class="col flex-row" action="" method="get">
                                                    <div class="mb-1">
                                                        <input class="form-control" type="date" name="get_date"
                                                            placeholder="Entré une date pour le filtrage">
                                                    </div>
                                                    <!-- <div class="mb-1">
                                                        <input class="form-control" type="text" name="get_name"
                                                            placeholder="Entré un nom pour le filtrage">
                                                    </div> -->
                                                    <div class="d-grid gap">
                                                        <button type="submit" class="btn btn-primary">SUBMIT</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </nav>
                                    </td>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th scope="row" class="fs-3">Livraison:</th>
                                        <td class="fs-4">{{ posts_livr.liv }} T</td>
                                    </tr>
                                    <tr>
                                        <th scope="row" class="fs-3">Casse:</th>
                                        <td class="fs-4">{{ posts_casse.cas }} casses</td>
                                    </tr>
                                    <tr>
                                        <th scope="row" class="fs-3">Ensache:</th>
                                        <td class="fs-4">{{ posts_ensache.ens }} sacs</td>
                                    </tr>
                                    <tr>
                                        <th scope="row" class="fs-3">Taux_Casse:</th>
                                        <td class="fs-4">{{ posts_tx_casse.tx_cas|floatformat:2 }} %</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="col">
                    <div class="card">
                        <div class="card-header fs-3 bg-primary text-center text-light btn"><i class="fas fa-book"></i>
                            Details
                        </div>
                        <div class="card-body">
                            <table class="table table-bordered">
                                <thead>
                                    <td colspan="2">
                                        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                                            <div class="container-fluid">
                                                <form class="col flex-row" action="" method="get">
                                                    <div class="mb-1">
                                                        <input class="form-control" type="date" name="get_date"
                                                            placeholder="Entré une date pour le filtrage">
                                                    </div>
                                                    <!-- <div class="mb-1">
                                                        <input class="form-control" type="text" name="get_name"
                                                            placeholder="Entré un nom pour le filtrage">
                                                    </div> -->
                                                    <div class="d-grid gap">
                                                        <button type="submit" class="btn btn-primary">SUBMIT</button>
                                                    </div>
                                                </form>
                                            </div>
                        </div>
                        </nav>
                        </td>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row" class="fs-3">Livraison:</th>
                                <td class="fs-4">{{ livr_total.liv }} T</td>
                            </tr>
                            <tr>
                                <th scope="row" class="fs-3">Casse:</th>
                                <td class="fs-4">{{ casse_total.cas }} casses</td>
                            </tr>
                            <tr>
                                <th scope="row" class="fs-3">Ensache:</th>
                                <td class="fs-4">{{ ensa_total.ens }} sacs</td>
                            </tr>
                            <tr>
                                <th scope="row" class="fs-3">Taux_Casse:</th>
                                <td class="fs-4">{{ tx_casse_total.tx_cas|floatformat:2 }} %</td>
                            </tr>
                        </tbody>
                        </table>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% else %}
<div class="text-center my-5">
    <p>Votre requette n'est pas prise en compte; cliqué sur <a href="{% url 'product:index' %}">Home</a> pour retourner
        sur la page!</p>
</div>
{% endif %}
</div>
{% endblock content %}

templates/navBar.html
<!-- <nav class="navbar navbar-expand-lg navbar-light bg-primary">
    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <i class="fas fa-house fa-2x"></i>
                    <a class="fs-4 text-light" href="{% url 'product:index' %}"> Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="breadcrumb-item fs-4">
                        <a class="fs-4 text-light" href="/details/?id_user={{ user.id }}"><i class="far fa-user"></i> {{ user.username|capfirst }}</a>
                    </li>
                {% endif %}
            </ol>
        </nav>
    </div>
    <div class="me-4">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                {% if user.is_authenticated %}
                <li class="breadcrumb-item fs-4">
                    <a class="fs-6 text-light" href="{% url 'users:logout' %}">Deconnexion</a>
                </li>
                {% if user.is_superuser %}
                <li class="breadcrumb-item fs-4">
                    <a class="fs-6 text-light" href="{% url 'users:logout' %}">salut</a>
                </li>
                {% endif %}
                {% else %}
                <li class="breadcrumb-item fs-4">
                    
                </li>
                {% endif %}
            </ol>
        </nav>
    </div>
</nav> -->
<nav class="navbar navbar-expand-lg navbar-primary bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand text-light fs-4" href="{% url 'product:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'product:index' %}">Home</a>
                </li> -->
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active text-light fs-6" href="/details/?id_user={{ user.id }}"><i class="far fa-user"></i> {{user.username|capfirst }}</a>
                </li>
                {% endif %}

            </ul>
            {% if user.is_superuser %}
                <form class="d-flex" method="get" action="#">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
                    <button class="btn btn-outline-light" type="submit">Search</button>
                </form>
            {% endif %}
            <div class="dropdown ms-5">
                {% if user.is_authenticated %}
                <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuAvatar"
                    role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                    <img src="https://mdbcdn.b-cdn.net/img/new/avatars/2.webp" class="rounded-circle" height="25"
                        alt="Black and White Portrait of a Man" loading="lazy" />
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">

                    <li>
                        <a class="dropdown-item" href="#">My profile</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="#">Settings</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                </ul>
                {% else %}
                <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuAvatar"
                    role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                    <img src="https://placehold.jp/006699/ffffff/150x150.png?text=No%20Image" class="rounded-circle"
                        height="25" alt="Black and White Portrait of a Man" loading="lazy" />
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuAvatar">

                    <li>
                        <a class="dropdown-item" href="{% url 'users:logup' %}">Logup</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% url 'users:login' %}">Login</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </div>
    </div>
</nav>